#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ ! -f "out/web-components/astra.bundle.js" ]; then
    echo "Error: Required file 'out/web-components/astra.bundle.js' is missing."
    exit 1
else
    exit 0
fi
